// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfCsUNkPIO5i7yh9IX1mMcJyb8V2spjHQ',
    appId: '1:1084346348105:web:4f95d7732d2545dece4598',
    messagingSenderId: '1084346348105',
    projectId: 'frontend-bbe5c',
    authDomain: 'frontend-bbe5c.firebaseapp.com',
    storageBucket: 'frontend-bbe5c.appspot.com',
    measurementId: 'G-DBTZMEX49H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaBOqtmcIDH2Oc6rnYgwGS52hMxzl5TsI',
    appId: '1:1084346348105:android:5a00cb7874231691ce4598',
    messagingSenderId: '1084346348105',
    projectId: 'frontend-bbe5c',
    storageBucket: 'frontend-bbe5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSjzctZkK_XmQ43svyGBQr9dBVReMMUuM',
    appId: '1:1084346348105:ios:456f9dcdb4709cf6ce4598',
    messagingSenderId: '1084346348105',
    projectId: 'frontend-bbe5c',
    storageBucket: 'frontend-bbe5c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSjzctZkK_XmQ43svyGBQr9dBVReMMUuM',
    appId: '1:1084346348105:ios:456f9dcdb4709cf6ce4598',
    messagingSenderId: '1084346348105',
    projectId: 'frontend-bbe5c',
    storageBucket: 'frontend-bbe5c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfCsUNkPIO5i7yh9IX1mMcJyb8V2spjHQ',
    appId: '1:1084346348105:web:97372a088eb097e7ce4598',
    messagingSenderId: '1084346348105',
    projectId: 'frontend-bbe5c',
    authDomain: 'frontend-bbe5c.firebaseapp.com',
    storageBucket: 'frontend-bbe5c.appspot.com',
    measurementId: 'G-LNBTPT7HFD',
  );
}
